apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohttp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohttp
  template:
    metadata:
      labels:
        app: gohttp
    spec:
      containers:
        - name: go-http
          image: geraldocoosta/go-apresentacao:58
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"

